import mysql.connector 

mydb =mysql.connector.connect(host="localhost",user="yash",passwd="Yj123456@",auth_plugin='mysql_native_password')
mycursor=mydb.cursor()
mycursor.execute("create database if not exists bank")
mydb.commit()
mycursor.execute("use bank")
mycursor.execute("create table if not exists profile(Holder varchar(50),Father varchar(50),Mother varchar(50),Date_of_birth varchar(10),Siblings varchar(2),Contact varchar(20),Email varchar(50),Address varchar(200),Account_num varchar(18))")
mydb.commit()
mycursor.execute("create table if not exists login(Account_num varchar(18),Password varchar(200))")
mydb.commit()
mycursor.execute("create table if not exists current_account(Account_num varchar(18),amount bigint)")
mydb.commit()
mycursor.execute("create table if not exists savings_account(Account_num varchar(18),amount bigint,interest int)")
mydb.commit()
mycursor.execute("create table if not exists credit_account(Account_num varchar(18),used bigint,limit_ bigint)")
mydb.commit()
mycursor.execute("create table if not exists salary_account(Account_num varchar(18),amount bigint)")
mydb.commit()
mycursor.execute("create table if not exists fixed_deposit_account(Account_num varchar(18),amount bigint,time_in_months smallint,interest int)")
mydb.commit()
mycursor.execute("create table if not exists recurring_deposit_account(Account_num varchar(18),amount bigint,time_in_months smallint,interest int)")
mydb.commit()